version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports: 
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    env_file:
      - './.env'
    volumes:
      - ./backend/src:/app/src
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - './.env'
    ports: 
      - ${REACT_APP_FRONTEND_PORT}:${REACT_APP_FRONTEND_PORT}
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: crm_postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
